- hosts: public
  become: yes
  vars_files:
    - vars/public.yml
  roles:
    - role: geerlingguy.firewall

- hosts: test
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.firewall