---
- name: basic secure package download and check
  hosts: all
  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: yes
    - name: baic-utils-package
      ansible.builtin.apt:
        state: present
        name: {{ item }}
      loop:
        - ftp
        - vim
        - net-tools
        - pwquality
        - tiger
        - snoopy