---
- name: Deploy beat configuration files
  hosts: all
  vars:
    logstash:
      - auditbeat
      - filebeat
      - metricbeat
  tasks:
  - name: Download yml file from FTP server
    command: curl -O --silent --user ftpuser:1234 ftp://10.11.1.2/upload/logstash_file/{{ item }}.yml
    loop: "{{ logstash }}"
  - name: Copy beat configuration files
    copy:
      src: "/home/server/{{ item }}.yml"
      dest: "/etc/{{ item }}/{{ item }}.yml"
      mode: 0644
    loop: "{{ logstash }}"

  - name: Restart filebeat service
    service:
      state: restarted
      name: filebeat 

  - name: Restart metricbeat service
    service:
      state: restarted
      name: metricbeat

  - name: Restart auditbeat service
    service:
      state: restarted
      name: auditbeat
